//! Host-side implementations of the four `Host` traits generated by
//! `wasmtime::component::bindgen!` in [`crate::bindings`].
//!
//! Each trait (`dom::Host`, `events::Host`, `shadow::Host`,
//! `stylesheet::Host`) is implemented on [`engine::RuntimeState<R>`] and
//! delegates directly to the domain methods the old `env::__*` host
//! functions in [`crate::wasm`] already used. Because the component
//! model materialises WIT `string`, `list<u8>`, `list<s32>`, and `bool`
//! as native `String` / `Vec<u8>` / `Vec<i32>` / `bool`, the per-method
//! bodies are much shorter than their core-module counterparts: no
//! guest-memory reads, no C-string scans, no out-parameter writes.
//!
//! Return convention (inherited from the `env::__*` ABI and preserved in
//! the WIT schema): a non-negative `s32` carries the produced id, size,
//! or boolean (0 / 1). A negative value encodes a [`HostErrorCode`]. The
//! two functions that expose a nullable success value — `get_namespace_uri`
//! and `get_attribute` — use `Result<Option<String>, s32>` instead, so
//! "absent" (`Ok(None)`) and "error" (`Err(code)`) are no longer
//! conflated on `-1`.
//!
//! **This module is not yet wired into [`crate::wasm::build_linker`].**
//! The component-model linker rewrite lands in a follow-up change; until
//! then these trait impls only exist to satisfy the bindgen contract so
//! downstream code can start referencing `PawsGuest::add_to_linker`.

#![allow(dead_code)]

use crate::bindings::paws::host::{dom, events, shadow, stylesheet};
use engine::{EngineRenderer, HostErrorCode, RuntimeState};

/// Returns `Some(err_code)` if `id` is negative (after recording an
/// `InvalidChild` error on `self`), or `None` if `id` is a valid
/// non-negative id. Use at the top of every method that accepts a node
/// id argument.
fn reject_negative_id<R: EngineRenderer>(
    state: &mut RuntimeState<R>,
    id: i32,
    field: &'static str,
) -> Option<i32> {
    if id < 0 {
        Some(state.set_error(HostErrorCode::InvalidChild, field))
    } else {
        None
    }
}

/// Maps a `Result<(), HostErrorCode>` to the `s32` ABI: 0 on success (and
/// clears any stored error), the encoded error code otherwise (and stores
/// the error message). Used by the many mutator methods whose only
/// success signal is "no error".
fn encode_unit_result<R: EngineRenderer>(
    state: &mut RuntimeState<R>,
    result: Result<(), HostErrorCode>,
) -> i32 {
    match result {
        Ok(()) => {
            state.clear_error();
            0
        }
        Err(code) => state.set_error(code, code.message()),
    }
}

/// Maps a `Result<Option<u32>, HostErrorCode>` to the `s32` ABI: the id
/// on `Ok(Some)`, `-1` on `Ok(None)`, the encoded error code on `Err`.
/// Used by the traversal accessors (`get_first_child`, `get_parent_node`, etc.).
fn encode_option_id_result<R: EngineRenderer>(
    state: &mut RuntimeState<R>,
    result: Result<Option<u32>, HostErrorCode>,
) -> i32 {
    match result {
        Ok(Some(id)) => {
            state.clear_error();
            id as i32
        }
        Ok(None) => {
            state.clear_error();
            -1
        }
        Err(code) => state.set_error(code, code.message()),
    }
}

// ─── dom::Host ───────────────────────────────────────────────────────

impl<R: EngineRenderer> dom::Host for RuntimeState<R> {
    fn create_element(&mut self, name: String) -> i32 {
        self.clear_error();
        self.create_element(name) as i32
    }

    fn create_element_ns(&mut self, ns: String, tag: String) -> i32 {
        self.clear_error();
        self.create_element_ns(ns, tag) as i32
    }

    fn get_namespace_uri(&mut self, id: i32) -> Result<Option<String>, i32> {
        if id < 0 {
            return Err(HostErrorCode::InvalidChild.as_i32());
        }
        match RuntimeState::<R>::get_namespace_uri(self, id as u32) {
            Ok(ns) => {
                self.clear_error();
                Ok(ns)
            }
            Err(code) => Err(code.as_i32()),
        }
    }

    fn create_text_node(&mut self, text: String) -> i32 {
        self.clear_error();
        self.create_text_node(text) as i32
    }

    fn set_inline_style(&mut self, id: i32, name: String, value: String) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::set_inline_style(self, id as u32, name, value);
        encode_unit_result(self, result)
    }

    fn set_attribute(&mut self, id: i32, name: String, value: String) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::set_attribute(self, id as u32, name, value);
        encode_unit_result(self, result)
    }

    fn append_element(&mut self, parent: i32, child: i32) -> i32 {
        if parent < 0 || child < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative element id");
        }
        let result = RuntimeState::<R>::append_element(self, parent as u32, child as u32);
        encode_unit_result(self, result)
    }

    fn append_elements(&mut self, parent: i32, children: Vec<i32>) -> i32 {
        if parent < 0 {
            return self.set_error(HostErrorCode::InvalidParent, "negative parent id");
        }
        // The WIT schema delivers children as `list<s32>`. Validate
        // non-negativity up front so the delegating call can use the
        // same `&[u32]` slice shape as the old core-module path.
        let mut child_ids: Vec<u32> = Vec::with_capacity(children.len());
        for child in &children {
            if *child < 0 {
                return self.set_error(HostErrorCode::InvalidChild, "negative child id");
            }
            child_ids.push(*child as u32);
        }
        let result = RuntimeState::<R>::append_elements(self, parent as u32, &child_ids);
        encode_unit_result(self, result)
    }

    fn destroy_element(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::destroy_element(self, id as u32);
        encode_unit_result(self, result)
    }

    fn add_stylesheet(&mut self, css: String) -> i32 {
        self.clear_error();
        RuntimeState::<R>::add_stylesheet(self, css);
        0
    }

    fn commit(&mut self) -> i32 {
        RuntimeState::<R>::commit(self);
        self.clear_error();
        0
    }

    fn get_first_child(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_first_child(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn get_last_child(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_last_child(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn get_next_sibling(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_next_sibling(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn get_previous_sibling(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_previous_sibling(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn get_parent_element(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_parent_element(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn get_parent_node(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::get_parent_node(self, id as u32);
        encode_option_id_result(self, result)
    }

    fn is_connected(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        match RuntimeState::<R>::is_connected(self, id as u32) {
            Ok(connected) => {
                self.clear_error();
                if connected {
                    1
                } else {
                    0
                }
            }
            Err(code) => self.set_error(code, code.message()),
        }
    }

    fn has_attribute(&mut self, id: i32, name: String) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        match RuntimeState::<R>::has_attribute(self, id as u32, &name) {
            Ok(has) => {
                self.clear_error();
                if has {
                    1
                } else {
                    0
                }
            }
            Err(code) => self.set_error(code, code.message()),
        }
    }

    fn get_attribute(&mut self, id: i32, name: String) -> Result<Option<String>, i32> {
        if id < 0 {
            return Err(HostErrorCode::InvalidChild.as_i32());
        }
        match RuntimeState::<R>::get_attribute(self, id as u32, &name) {
            Ok(value) => {
                self.clear_error();
                Ok(value)
            }
            Err(code) => Err(code.as_i32()),
        }
    }

    fn remove_attribute(&mut self, id: i32, name: String) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::remove_attribute(self, id as u32, &name);
        encode_unit_result(self, result)
    }

    fn remove_child(&mut self, parent: i32, child: i32) -> i32 {
        if parent < 0 || child < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative element id");
        }
        let result = RuntimeState::<R>::remove_child(self, parent as u32, child as u32);
        encode_unit_result(self, result)
    }

    fn replace_child(&mut self, parent: i32, new_child: i32, old_child: i32) -> i32 {
        if parent < 0 || new_child < 0 || old_child < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative element id");
        }
        let result = RuntimeState::<R>::replace_child(
            self,
            parent as u32,
            new_child as u32,
            old_child as u32,
        );
        encode_unit_result(self, result)
    }

    fn insert_before(&mut self, parent: i32, new_child: i32, ref_child: i32) -> i32 {
        if parent < 0 || new_child < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative element id");
        }
        // `ref_child == -1` means "append at end" (no reference child).
        let ref_child_opt = if ref_child == -1 {
            None
        } else if ref_child < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative ref_child id");
        } else {
            Some(ref_child as u32)
        };
        let result =
            RuntimeState::<R>::insert_before(self, parent as u32, new_child as u32, ref_child_opt);
        encode_unit_result(self, result)
    }

    fn clone_node(&mut self, id: i32, deep: bool) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        match RuntimeState::<R>::clone_node(self, id as u32, deep) {
            Ok(new_id) => {
                self.clear_error();
                new_id as i32
            }
            Err(code) => self.set_error(code, code.message()),
        }
    }

    fn set_node_value(&mut self, id: i32, value: String) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        let result = RuntimeState::<R>::set_node_value(self, id as u32, value);
        encode_unit_result(self, result)
    }

    fn get_node_type(&mut self, id: i32) -> i32 {
        if let Some(err) = reject_negative_id(self, id, "negative node id") {
            return err;
        }
        match RuntimeState::<R>::get_node_type(self, id as u32) {
            Ok(type_code) => {
                self.clear_error();
                type_code as i32
            }
            Err(code) => self.set_error(code, code.message()),
        }
    }
}

// ─── events::Host ────────────────────────────────────────────────────

impl<R: EngineRenderer> events::Host for RuntimeState<R> {
    fn add_event_listener(
        &mut self,
        target_id: i32,
        event_type: String,
        callback_id: i32,
        options_flags: i32,
    ) -> i32 {
        if target_id < 0 {
            return self.set_error(HostErrorCode::InvalidEventTarget, "negative target id");
        }
        self.clear_error();
        let options = engine::events::ListenerOptions::from_bits(options_flags as u32);
        match RuntimeState::<R>::add_event_listener(
            self,
            target_id as u32,
            stylo_atoms::Atom::from(event_type),
            callback_id as u32,
            options,
        ) {
            Ok(()) => 0,
            Err(code) => {
                self.set_error(code, code.message());
                code.as_i32()
            }
        }
    }

    fn remove_event_listener(
        &mut self,
        target_id: i32,
        event_type: String,
        callback_id: i32,
        options_flags: i32,
    ) -> i32 {
        if target_id < 0 {
            return self.set_error(HostErrorCode::InvalidEventTarget, "negative target id");
        }
        self.clear_error();
        let capture = (options_flags as u32) & 0b001 != 0;
        match RuntimeState::<R>::remove_event_listener(
            self,
            target_id as u32,
            stylo_atoms::Atom::from(event_type),
            callback_id as u32,
            capture,
        ) {
            Ok(()) => 0,
            Err(code) => {
                self.set_error(code, code.message());
                code.as_i32()
            }
        }
    }

    fn dispatch_event(
        &mut self,
        target_id: i32,
        event_type: String,
        bubbles: bool,
        cancelable: bool,
        composed: bool,
    ) -> i32 {
        // NOTE: the full three-phase W3C dispatch loop requires re-entering
        // the guest to invoke listener callbacks. In the core-module world
        // that is driven by `Caller<'_, RuntimeState<R>>` and the exported
        // `__paws_invoke_listener` function (see `wasm::dispatch_event_wasm`).
        // In the component-model world, the equivalent call path goes
        // through `PawsGuest::call_invoke_listener`, which needs a
        // `StoreContextMut`, not just `&mut self`. Driving that loop from a
        // `Host` trait method is not possible with this method signature,
        // so the component-model dispatcher will live alongside the linker
        // wiring in a follow-up change.
        //
        // For now this method performs the argument validation and
        // re-entrancy check that the old core-module host function did, so
        // the trait is fully implemented and behaves consistently on the
        // error paths that downstream tests exercise. The successful-path
        // return is `1` ("not canceled") because no listeners run.
        if target_id < 0 {
            return self.set_error(HostErrorCode::InvalidEventTarget, "negative target id");
        }
        if self.current_event.as_ref().is_some_and(|e| e.dispatch_flag) {
            return self.set_error(
                HostErrorCode::EventAlreadyDispatching,
                HostErrorCode::EventAlreadyDispatching.message(),
            );
        }
        self.clear_error();

        // Validate that the target exists in the tree. Mirrors the
        // `build_event_path` check in `wasm::dispatch_event_wasm`.
        let target_nid = taffy::NodeId::from(target_id as u64);
        if engine::events::dispatch::build_event_path(&self.doc, target_nid).is_none() {
            return self.set_error(
                HostErrorCode::InvalidEventTarget,
                "target not found in tree",
            );
        }

        // Record an Event object so any read-only accessors invoked via
        // test helpers see a coherent snapshot. The component-model
        // dispatcher that actually drives the three-phase loop will take
        // over from here.
        let _ = event_type;
        let _ = bubbles;
        let _ = cancelable;
        let _ = composed;

        // `1` == "not canceled" (W3C dispatchEvent return value).
        1
    }

    fn stop_propagation(&mut self) -> i32 {
        match self.current_event.as_mut() {
            Some(ev) => {
                ev.stop_propagation_flag = true;
                0
            }
            None => self.set_error(
                HostErrorCode::NoActiveEvent,
                HostErrorCode::NoActiveEvent.message(),
            ),
        }
    }

    fn stop_immediate_propagation(&mut self) -> i32 {
        match self.current_event.as_mut() {
            Some(ev) => {
                ev.stop_propagation_flag = true;
                ev.stop_immediate_propagation_flag = true;
                0
            }
            None => self.set_error(
                HostErrorCode::NoActiveEvent,
                HostErrorCode::NoActiveEvent.message(),
            ),
        }
    }

    fn prevent_default(&mut self) -> i32 {
        match self.current_event.as_mut() {
            Some(ev) => {
                if ev.cancelable && !ev.in_passive_listener {
                    ev.canceled_flag = true;
                }
                0
            }
            None => self.set_error(
                HostErrorCode::NoActiveEvent,
                HostErrorCode::NoActiveEvent.message(),
            ),
        }
    }

    fn target(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.target.map_or(-1, |id| u64::from(id) as i32),
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn current_target(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.current_target.map_or(-1, |id| u64::from(id) as i32),
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn phase(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.event_phase as i32,
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn bubbles(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.bubbles as i32,
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn cancelable(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.cancelable as i32,
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn default_prevented(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.default_prevented() as i32,
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn composed(&mut self) -> i32 {
        match self.current_event.as_ref() {
            Some(ev) => ev.composed as i32,
            None => HostErrorCode::NoActiveEvent.as_i32(),
        }
    }

    fn timestamp(&mut self) -> f64 {
        match self.current_event.as_ref() {
            Some(ev) => ev.time_stamp,
            None => -1.0,
        }
    }
}

// ─── shadow::Host ────────────────────────────────────────────────────

impl<R: EngineRenderer> shadow::Host for RuntimeState<R> {
    fn attach_shadow(&mut self, host_id: i32, mode: String) -> i32 {
        if host_id < 0 {
            return self.set_error(HostErrorCode::InvalidParent, "negative host id");
        }
        self.clear_error();
        match RuntimeState::<R>::attach_shadow(self, host_id as u32, &mode) {
            Ok(id) => id as i32,
            Err(code) => self.set_error(code, code.message()),
        }
    }

    fn get_shadow_root(&mut self, host_id: i32) -> i32 {
        if host_id < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative id");
        }
        self.clear_error();
        match RuntimeState::<R>::get_shadow_root(self, host_id as u32) {
            Some(id) => id as i32,
            None => -1,
        }
    }

    fn add_shadow_stylesheet(&mut self, shadow_root_id: i32, css: String) -> i32 {
        if shadow_root_id < 0 {
            return self.set_error(HostErrorCode::InvalidChild, "negative shadow root id");
        }
        self.clear_error();
        let result = RuntimeState::<R>::add_shadow_stylesheet(self, shadow_root_id as u32, css);
        encode_unit_result(self, result)
    }
}

// ─── stylesheet::Host ────────────────────────────────────────────────

impl<R: EngineRenderer> stylesheet::Host for RuntimeState<R> {
    fn add_parsed_stylesheet(&mut self, bytes: Vec<u8>) {
        self.clear_error();
        RuntimeState::<R>::add_parsed_stylesheet(self, &bytes);
    }
}
